Platform_Developer_II_Lightning/objects/Boat__c.object
<CustomObject>
    <fields>
        <fullName>BoatType__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Boat Type</label>
        <referenceTo>BoatType__c</referenceTo>
        <relationshipLabel>Boats</relationshipLabel>
        <relationshipName>Boats</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Boats</relationshipLabel>
        <relationshipName>Boats</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Length__c</fullName>
        <inlineHelpText>In feet</inlineHelpText>
        <label>Length</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Picture__c</fullName>
        <label>Picture</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <inlineHelpText>Estimated Pric</inlineHelpText>
        <label>Price</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Year_Built__c</fullName>
        <label>Year Built</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Boat</label>
    <nameField>
        <label>Boat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boats</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/BoatType__c.object
<CustomObject>
    <label>Boat Type</label>
    <nameField>
        <label>Boat Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boat Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BoatSearchResults.cls
public class BoatSearchResults {
	@AuraEnabled
    public static List<Boat__c> getBoats(String boatTypeId){
        if(String.isNotBlank(boatTypeId)){
            return [SELECT Id, Name, Contact__c, Contact__r.Name, Contact__r.HomePhone, Contact__r.Email, BoatType__c, 
                    Description__c, Geolocation__Latitude__s, Geolocation__Longitude__s, Length__c, BoatType__r.Name, 
                    Picture__c, Price__c, Year_Built__c FROM Boat__c WHERE BoatType__c =: boatTypeId];
        }else{
        	return [SELECT Id, Name, Contact__c, Contact__r.Name, Contact__r.HomePhone, Contact__r.Email, BoatType__c, 
                    Description__c, Geolocation__Latitude__s, Geolocation__Longitude__s, Length__c, BoatType__r.Name, 
                    Picture__c, Price__c, Year_Built__c FROM Boat__c];
        }
    }
    
    @AuraEnabled
    public static List<BoatType__c> getBoatTypes(){
        return [SELECT Id, Name FROM BoatType__c Order BY Name ASC];
    }
}